In [1]:
!pip install numpy

In [8]:
import numpy as np
arr=[10,20,30,40]
print(arr[0])   
print(arr[2])   
print(arr[-1]) 
print(arr)

10
30
40
[10, 20, 30, 40]


In [10]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0, 1])   
print(arr)

2
[[1 2 3]
 [4 5 6]]


In [11]:
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])
print(arr[0, 1, 1])

print(arr)

5
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
